### PR TITLE
fix: prevent on conflict error

### LINKED ISSUE #47: Resuming ingestion sometimes fails
## How to reproduce
- Start the indexer
- Run the indexer for until everything is synced
- Stop the indexer
- Restart the indexer after sometime

You will encounter such errors
```log
ERROR quasar_indexer::ingestion - Error while ingesting ledgers: DbError(Query(SqlxError(Database(PgDatabaseError { 
severity: Error, code: "23505", message: "duplicate key value violates unique constraint \"accounts_pkey\"", detail: Some("Key 
(id)=(GC4FO7D2X4ZGLGZ6BR535K627KLFW5ZW5LK2GIQIX5L4T7WDURQ6YHOL) already exists."), hint: None, position: 
None, where: None, schema: Some("public"), table: Some("accounts"), column: None, data_type: None, constraint: 
Some("accounts_pkey"), file: Some("nbtinsert.c"), line: Some(664), routine: Some("_bt_check_unique") }))))
```

### PR DESCRIPTION
**Pull request by geofmureithi**
Tries to close #47

### CODE REVIEW

File: src/ingestion/accounts.rs [hunk 1]
```diff
@@ -38,7 +39,13 @@ pub(super) async fn ingest_account(
 ) -> Result<(), IngestionError> {
     let account: account::ActiveModel = account::ActiveModel::try_from(account)?;
 
-    account.insert(db.as_inner()).await?;
-
+    account::Entity::insert(account)
+        .on_conflict(
+            OnConflict::column(account::Column::Id)
+                .update_columns([account::Column::LastModified, account::Column::Balance])
```
Comment (tomekpiotrowski) [inline src/ingestion/accounts.rs:45]: I think we should be updating a lot more columns here. Actually probably all columns expect the id and createdAt.

File: src/ingestion/contracts.rs [hunk 2]
```diff
@@ -47,7 +46,14 @@ async fn ingest_contract(
     let sequence = contract.lastmodified;
     info!("Ingesting contract since {}", sequence);
     let contract: contract::ActiveModel = contract::ActiveModel::try_from(contract).unwrap();
-    contract.insert(&**database).await?;
+    contract::Entity::insert(contract)
+        .on_conflict(
+            OnConflict::column(contract::Column::Address)
+                .update_columns([contract::Column::LastModified])
```
Comment (tomekpiotrowski) [inline src/ingestion/contracts.rs:52]: Same applies here.

**Review by tomekpiotrowski — CHANGES_REQUESTED** [review]

File: src/ingestion/accounts.rs (hunk 1 above)
Comment (geofmureithi) [reply src/ingestion/accounts.rs]: Resolved in https://github.com/eigerco/quasar/pull/63/commits/8089fbce28c416bd942c26e12903eb644cff7926

**Review by tomekpiotrowski — APPROVED** [review]
